---

- name: install docker
  become: yes
  apt:
    name:
      - docker.io
      - docker-compose
    state: latest
- name: Start Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
