---

- name: Copy node-discovery job
  copy: src=node-discovery dest=/root/

- name: Create log directory
  file: path=/var/log/node-discovery state=directory

- name: Install python
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install python dependencies
  shell: pip3 install -r /root/node-discovery/requirements.txt

- name: Install node-discovery job
  cron:
    name: "Discover nomad nodes"
    month: "*"
    weekday: "*"
    day: "*"
    hour: "*"
    minute: "*"
    job: "/usr/bin/python3 /root/node-discovery/node-discovery.py > /var/log/node-discovery/node-discovery.log 2>&1"
    disabled: "no"
