---

- name: Provision node
  hosts: localhost
  connection: local
  become: yes
  roles:
    - role: common/base
    - role: cron/node-discovery
    - role: orchestration/nomad
#    - role: orchestration/consul
